//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestBridgeEmulator.Emulator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ColorsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ColorsSettings defaultInstance = ((ColorsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ColorsSettings())));
        
        public static ColorsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffca86")]
        public string EMPTY {
            get {
                return ((string)(this["EMPTY"]));
            }
            set {
                this["EMPTY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("996666")]
        public string NEED_ANODE_REPLACE {
            get {
                return ((string)(this["NEED_ANODE_REPLACE"]));
            }
            set {
                this["NEED_ANODE_REPLACE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a47c45")]
        public string ANODE_REPLACED {
            get {
                return ((string)(this["ANODE_REPLACED"]));
            }
            set {
                this["ANODE_REPLACED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d4b851")]
        public string UNSCHEDULED_ANODE_REPLACEMENT {
            get {
                return ((string)(this["UNSCHEDULED_ANODE_REPLACEMENT"]));
            }
            set {
                this["UNSCHEDULED_ANODE_REPLACEMENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e60548")]
        public string CANCELED_ANODE_REPLACE {
            get {
                return ((string)(this["CANCELED_ANODE_REPLACE"]));
            }
            set {
                this["CANCELED_ANODE_REPLACE"] = value;
            }
        }
    }
}
